INSERT INTO public.muleapplication (id,name,contactperson,contactpersoninitials,projectname,onboardingagreementid,status,category,costcenterlabel) VALUES
	 ('Et8uGOBT73','automatic-sample-preparation-exp-v1','Alejandrina Annabel','ALAN','Omni Tech','CsW-JCUiJA','FAILED','KNOWN','LD'),
	 ('5r_7-DjV1w','clinical-data-notify-hot-prc-v1','Anjela Boyd','ANBO','Fellowship Investments','KnuhRrTdlw','PENDING','UNKNOWN','ZD'),
	 ('5lbOc9UOU1','icm-registration-v1','Annmaria Bride','ANBR','Environ Architectural Design','cJ4pmOXQzN','PENDING','KNOWN','RS'),
	 ('smzCmcNX9Q','document-management-v1','Almeta Albin','ALAL','Galaxy Man','NelKAOFhKo','FAILED','UNKNOWN','ZD'),
	 ('YA2wwAUWnT','nnameo-israel-calls-v1','Ava Bennoune','AVBE','Network Air','VtbtEAgn6t','DEPLOYED','UNKNOWN','RS'),
	 ('Tn0QVlUu1-','meet-ioengage-sys-v1','Audie Bausa','AUBA','Circuit Design','v4be7wMJeB','DEPLOYED','UNKNOWN','AD'),
	 ('m5MjvnhoLn','scicap-slb-v1','Cammi Annabel','CAAN','Cut Above','8hdkQs1NHY','FAILED','UNKNOWN','RS'),
	 ('sI2S2TgiPu','mdm-bsp-update-api-v1','Addia Carli','ADCA','Indiewealth','ExKVX1ZG9B','FAILED','KNOWN','ZD'),
	 ('KnxfAr4jcG','veeva-vault-rim-registrations-v1','Cairistiona Cabrera','CACA','One-Up Realtors','RU0TOyaMEI','FAILED','UNKNOWN','AD'),
	 ('qcsVVDZK3Q','patient-tracker-v1','Beverlie Abito','BEAB','Pearl Architectural Design','A2N4wMMK6h','PENDING','UNKNOWN','LD');
INSERT INTO public.muleapplication (id,name,contactperson,contactpersoninitials,projectname,onboardingagreementid,status,category,costcenterlabel) VALUES
	 ('k8tS-33YO4','cdm-registration-v1','Carolynn Braje','CABR','Grade A Investment','kK4z2LhH2o','PENDING','UNKNOWN','AD'),
	 ('qBtWGAI1vE','document-notification-v1','Bryn Bock','BRBO','Freedom Map','3YnUD0mRAc','FAILED','KNOWN','ZD'),
	 ('hU7YiGZ4GW','lift-poc-v1','Bobine Beckert','BOBE','Opti-Tek','v7jRyG5RY8','PENDING','KNOWN','LD'),
	 ('5yXGn4uzNF','patient-copay-registration-v1','Alanna Abito','ALAB','Multi-Systems Merchant Services','YxNqxOba1f','DEPLOYED','UNKNOWN','LD'),
	 ('M3jtPR6ltt','mdm-onetrust-upsert-api-v1','Amaleta Berse','AMBE','Gas Zone','StLPe7Gfkg','PENDING','UNKNOWN','ZD'),
	 ('bsTLnGvOVb','rtsm-outbound-v0','Annmarie Barbara','ANBA','Envirotecture Design Service','lrNz6hrSzn','PENDING','KNOWN','AD'),
	 ('30crTUikVU','legacy-ctms-iwrs-int-v1','Alejandrina Beachclub','ALBE','Bold Ideas','iQgmUfEQ0F','FAILED','UNKNOWN','CS'),
	 ('8XGpD_hKNY','nextgen-sys-v1','Carlotta Atkinson','CAAT','Magik Grey','jng7fIrKxW','FAILED','UNKNOWN','RS'),
	 ('VzgBhf5PFc','cdr-irt-exp-v1','Alexandrina Bolin','ALBO','Planet Profit','T5bBRqIihF','PENDING','UNKNOWN','CS'),
	 ('MYQ6-R57ud','novoglow-ioccs-prc-v1','Berty Aranda','BEAR','Afforda Merchant Services','3eIcMmKst0','PENDING','KNOWN','ZD');
INSERT INTO public.muleapplication (id,name,contactperson,contactpersoninitials,projectname,onboardingagreementid,status,category,costcenterlabel) VALUES
	 ('Rj9207trCD','nn-patient-login-sys-v1','Bren Acra','BRAC','Environ Architectural Design','fM4fM7TWGG','DEPLOYED','UNKNOWN','LD'),
	 ('R1oJnoPYcJ','rtsm-outbound-v2','Aurore Barba','AUBA','Asian Plan','E0y1IMwmcY','FAILED','UNKNOWN','AD'),
	 ('IOFZoynAZx','patient-consent-v1','Betsey Braga','BEBR','Hoyden','ulpOVkLpjs','FAILED','KNOWN','ZD'),
	 ('FAOmJfEP4_','uagk-test-2023020703-v1','Adrea Barbã©','ADBA','Custom Lawn Care','qist4H_6c1','DEPLOYED','KNOWN','CS'),
	 ('C0z1KZlcmq','cnd-service-v1','Aurilia Cardell','AUCA','Gamma Grays','WSrNNfBwUl','DEPLOYED','UNKNOWN','LD'),
	 ('JLeMAP8ZLH','snowflake-db-sys-v1','Allene Carissa','ALCA','Magik Gray','xEPNgeIlS-','PENDING','KNOWN','CS'),
	 ('9D1LsDgmId','jkye-rd-prx-tpl-v1','Benedikta Cardell','BECA','Monit','Q5EVB8L8hS','PENDING','KNOWN','RS'),
	 ('F-evZr-thg','veeva-crm-snf-evnt-prc-v1','Brynne Bloggs','BRBL','Creative Wealth','K6qhaXbmeF','DEPLOYED','KNOWN','CS'),
	 ('r0JPMx5HFH','sfc-registration-v1','Alaine Amiralai','ALAM','Magna Architectural Design','gw-1f0gjID','FAILED','KNOWN','LD'),
	 ('e9aSeCOImd','ioccs-ioengage-prc-v1','Andy Bisson','ANBI','Destiny Realty','aSsVMejpIH','FAILED','KNOWN','ZD');
INSERT INTO public.muleapplication (id,name,contactperson,contactpersoninitials,projectname,onboardingagreementid,status,category,costcenterlabel) VALUES
	 ('nSs8HcLdKX','on24-ioengage-sys-v1','Ashlee Calafell','ASCA','First Choice Garden Maintenance','oxxaEOVsGf','DEPLOYED','UNKNOWN','AD'),
	 ('1cmgxNweVk','evs-benefit-verification-v1','Annora Bugovics','ANBU','Monk Home Funding Services','P-q88rWVZm','PENDING','UNKNOWN','ZD'),
	 ('5SlttLDkhA','oauth2-ioengage-prc-v1','Alfi Blauser','ALBL','Afforda Merchant Services','J_z7F1jfpW','DEPLOYED','UNKNOWN','ZD'),
	 ('NVEyvS7KWB','mdm-party-exp-v1','Becka Brickley','BEBR','Maxi-Tech','CQkBAHExkA','PENDING','KNOWN','CS'),
	 ('q7gxxURVJa','ioccs-emea-translate-utility-v1','Allis Azpeitia','ALAZ','Asian Answers','jYSCBCVIS1','FAILED','UNKNOWN','CS'),
	 ('sa9tb0xK57','clinical-vault-spark-exp-api-v1','Carlynn Campos','CACA','Earthworks Yard Maintenance','MJYbrneRO2','FAILED','UNKNOWN','CS'),
	 ('RKkMzedEx0','oce-marketing-party-sys-v1','Beryl Calafell','BECA','Infinite Wealth','Ie6e_8FHVJ','PENDING','UNKNOWN','ZD'),
	 ('RT7FQFvxbb','aws-clin-sys-v1','Catarina Bizari','CABI','Monlinks','HB0nVNgjxD','PENDING','KNOWN','AD'),
	 ('aH_yd4i5oD','ioccs-io-translate-utility-v1','Cahra Barbã©','CABA','Benesome','xgFpWpoupP','PENDING','KNOWN','CS'),
	 ('tx82ZGlQEe','novo-web-veevavault-exp-v1','Cassandry Biggi','CABI','One-Up Realty','FOTrTB3CkO','PENDING','KNOWN','ZD');
INSERT INTO public.muleapplication (id,name,contactperson,contactpersoninitials,projectname,onboardingagreementid,status,category,costcenterlabel) VALUES
	 ('JGgDWbFYWx','mdm-jms-queue-api-v1','Ameline Best','AMBE','Integra Investment Service','LLXLS4I-FN','PENDING','UNKNOWN','AD'),
	 ('jqno0_tD3P','sf-ioccs-lookup-sys-v1','Ailyn Cabrera','AICA','Perisolution','4PPw4PefMl','FAILED','KNOWN','CS'),
	 ('DjWhgcBHRB','references-translations-v1','Biddie Agass','BIAG','Landskip Yard Service','H-N7VFFaM7','FAILED','KNOWN','AD'),
	 ('_5lgGS902x','splunk-log-forwarder-v1','Bekki Benavidez','BEBE','Parts and Pieces','6ptKgZctCe','PENDING','UNKNOWN','RS'),
	 ('CXcl0BBmzJ','map-demo-patient-v1','Averyl Byrne','AVBY','Macroserve','3nEvUIZqEj','PENDING','KNOWN','ZD'),
	 ('CkRAWzDVd0','cdm-jms-consumer-v1','Bel Bitak','BEBI','Eden Lawn Service','N0S8T5v6B5','FAILED','UNKNOWN','CS'),
	 ('V84veNVZf0','dummy-sys-v2','Alameda Bobish','ALBO','Garden Guru','f_xfxjKkcm','PENDING','KNOWN','ZD'),
	 ('WgWRZPbVws','patient-cardreader-v1','Amalea Berse','AMBE','Gas Zone','AUcMYcZmCf','DEPLOYED','UNKNOWN','AD'),
	 ('JLDKKm90NL','patient-benefit-verification-v1','Caryl Ansel','CAAN','Earthworks Yard Maintenance','aomiCXsH5a','DEPLOYED','UNKNOWN','AD'),
	 ('7AG-jbZuix','uagk-test-2023020702-v1','Blaire Beachcub','BLBE','Buena Vista Realty Service','LLn0GqH3Yc','FAILED','UNKNOWN','AD');
INSERT INTO public.muleapplication (id,name,contactperson,contactpersoninitials,projectname,onboardingagreementid,status,category,costcenterlabel) VALUES
	 ('9rjwHGetb7','dow-jones-sys-v1','Adella Annitto','ADAN','Omni Source','LvqcMbSTwV','FAILED','UNKNOWN','CS'),
	 ('TWtMXK3F6Z','gta-exp-v1','Alexi Adellano','ALAD','Muscle Factory','FIuIl9ghFb','FAILED','UNKNOWN','CS'),
	 ('LHE9SJxU7i','mdm-sys-v1','Avivah Bayardo','AVBA','Buena Vista Garden Maintenance','QCMT7HXADD','FAILED','KNOWN','ZD'),
	 ('dOmzZjhYja','clinical-data-notify-nnexus-prc-v1','Cammy Alan','CAAL','Planetbiz','obM6X3TPx5','PENDING','UNKNOWN','ZD'),
	 ('PRju09aCtH','nextgen-ioccs-v2','Angeline Arcery','ANAR','Hoyden','Z3pZ1knO1y','DEPLOYED','KNOWN','CS'),
	 ('MlEoIEOSgb','vonage-callrecord-sys-v1','Avrit Best','AVBE','Asiatic Solutions','AUxiRHQU5I','DEPLOYED','KNOWN','RS'),
	 ('5Yg5hjWVK4','meet-search-ioengage-sys-v1','Barb Caldwell','BACA','Plan Future','66uR6cuRV8','DEPLOYED','KNOWN','AD'),
	 ('-HDK5fn3Pt','patient-registration-v1','Ainslee Alcapone','AIAL','Monk Home Improvements','P6kEHXKWrM','FAILED','UNKNOWN','ZD'),
	 ('vcpjwsILdv','patient-survey-v1','Name Betz','NABE','Mission You','-BFo2W7i58','PENDING','UNKNOWN','LD'),
	 ('2GuwS5CH3J','clinical-data-database-sys-v2','Brittany Brudzynski','BRBR','Golden Joy','YGVqvpuOgl','FAILED','KNOWN','AD');
INSERT INTO public.muleapplication (id,name,contactperson,contactpersoninitials,projectname,onboardingagreementid,status,category,costcenterlabel) VALUES
	 ('8ji_UWkn-a','patient-income-verification-v1','Bel Berardi','BEBE','Newhair','8lG06ObMUk','PENDING','UNKNOWN','AD'),
	 ('p6Cdcii3r3','ioccs-ioengage-sys-v1','Annie Bryant','ANBR','Cut Rite Lawn Care','3iCV_-nFUo','FAILED','KNOWN','LD'),
	 ('OUWbx_hPDO','scicap-prx-v1','Alicea Amarainy','ALAM','Jackhammer Technologies','4RIPajCPUT','PENDING','KNOWN','ZD'),
	 ('-ceBSDv7ET','mgage-optout-v1','Brooks Bah','BRBA','New World','OyJjAbYzuR','DEPLOYED','UNKNOWN','RS'),
	 ('tMhA5gEkNg','isotrain-sys-v1','Amandy Alegrias','AMAL','Edge Yard Service','y6ut0KRZd8','FAILED','UNKNOWN','ZD'),
	 ('Kz3STsaw4O','cdr-rtsm-shipment-request-exp-v1','Abbie Braga','ABBR','First Choice Garden Maintenance','DyVM5485Vd','PENDING','KNOWN','ZD'),
	 ('BL3cwWiaZe','azure-storage-sys-v1','Avrit Biersack','AVBI','Pearl Architectural Design','E4loEbnKFC','DEPLOYED','KNOWN','LD'),
	 ('m1AxBfZdAX','veeva-vault-clinical-sys-v1','Caresse Bts','CABT','Monit','j0Z7hs6mFA','FAILED','UNKNOWN','CS'),
	 ('RLGiTTopLB','globallims-exp-v1','Bonnibelle Abraham','BOAB','Garden Master','5youSCt7im','PENDING','UNKNOWN','RS'),
	 ('N3TZGXB3Vk','platformevents-supplyenrollment-v1','Bendite Buckley','BEBU','Bold Ideas','mWPLWolRKB','PENDING','KNOWN','LD');
INSERT INTO public.muleapplication (id,name,contactperson,contactpersoninitials,projectname,onboardingagreementid,status,category,costcenterlabel) VALUES
	 ('0NFRPpCJwu','vonage-callrecord-sys-v2','Ambur Andrews','AMAN','Multicerv','-wkvPEpul2','DEPLOYED','KNOWN','AD'),
	 ('c09kezKkvc','consent-management-v1','Aili Altamirano','AIAL','New World','HDTNcUVU1G','PENDING','UNKNOWN','LD'),
	 ('MqD4Jfi4OY','sf-ioccs-cases-prc-v1','Annis Alverã ','ANAL','Fireball','BnNwc6SRuA','DEPLOYED','KNOWN','ZD'),
	 ('erK_T8sXKq','io-e1d-novodemo-sys-v1-v1','Candra Benbow.','CABE','Magna Wealth','pZCQ8eofwN','FAILED','UNKNOWN','AD'),
	 ('UfL3o9OxbC','oce-sales-party-sys-v1','Anni Andersen','ANAN','Cougar Investment','FibmzEmm6q','PENDING','UNKNOWN','RS'),
	 ('rIaT_7lDG0','nnexus-public-exp-v1','Angelique Batuski','ANBA','Omni Realty','2LGdmRm8EJ','PENDING','UNKNOWN','RS'),
	 ('qSwVvU-nRZ','prw-safe-needledisposal-v1','Bernie Burack','BEBU','MegaSolutions','hFzebvLFor','FAILED','UNKNOWN','AD'),
	 ('XQmvCu385h','scicap-lambda-prx-v1','Alanah Bondarev','ALBO','Magna Wealth','Dw0CY48nZr','FAILED','UNKNOWN','CS'),
	 ('teF279d3YL','email-verification-v1','Cass Berse','CABE','Earthworks Garden Kare','9FPJWS9QZa','FAILED','UNKNOWN','CS'),
	 ('LwZhGdMCij','nvision-ioengage-aameo-sys-v1','Blondell Bad','BLBA','Intelli Wealth Group','sCwysSJT9V','FAILED','UNKNOWN','LD');
INSERT INTO public.muleapplication (id,name,contactperson,contactpersoninitials,projectname,onboardingagreementid,status,category,costcenterlabel) VALUES
	 ('_J5MTUytI1','patient-search-v1','Adan Canfield','ADCA','Indiewealth','LcYIB9tCnr','PENDING','KNOWN','ZD'),
	 ('Q5RnUIbtnJ','veeva-crm-sys-v1','Arda Barrenechea','ARBA','Gamma Grays','0QJSuzlkfA','PENDING','KNOWN','LD'),
	 ('B5LICp38Mn','zmsd-pilot-application-v1','Andromache Beli','ANBE','Personal & Corporate Design','JpGABMAZxe','DEPLOYED','KNOWN','LD'),
	 ('k0csoLSVsZ','crx-registration-v2','Bernetta Agin','BEAG','Mikro Designs','SHS2-kKeUl','DEPLOYED','UNKNOWN','AD'),
	 ('6Atg3u-r-6','audit-log-aggregator-v1','Alicea Bowman','ALBO','Infinity Investment Plan','TNZX_72IRg','DEPLOYED','UNKNOWN','CS'),
	 ('t8pu7jLcha','customer-complaint-ai-sys-v1','Avril Brunet','AVBR','Grey Fade','T6kMuIT2Mp','FAILED','KNOWN','ZD'),
	 ('Sx5hpwdy11','sims-exp-v1','Bellina Arellanos','BEAR','Landskip Yard Service','lWV7rBmVf_','PENDING','UNKNOWN','RS'),
	 ('I2iIqzUlfs','mdm-exp-v1','April Brown','APBR','Lawn N'' Order Garden Care','B5_iEBkXCd','FAILED','KNOWN','RS'),
	 ('BJY0ieqZfm','icm-message-delivery-v1','Amelina Beaird','AMBE','Asian Solutions','KUQWF9GbfQ','FAILED','KNOWN','LD'),
	 ('omWZFQUeCQ','cdr-participants-exp-v1','Beth Bolam','BEBO','Libera','ihg4r1S1X0','DEPLOYED','KNOWN','RS');
INSERT INTO public.muleapplication (id,name,contactperson,contactpersoninitials,projectname,onboardingagreementid,status,category,costcenterlabel) VALUES
	 ('O8ChiKX8Vo','send-notifications-v1','Bernardina Angus','BEAN','Fresh Start','s_bmYVJ50Y','PENDING','KNOWN','LD'),
	 ('mAF629Anmt','pas-x-poc-v1','Atlanta Aloisio','ATAL','Independent Wealth Management','3Je7bP9LWl','FAILED','KNOWN','AD'),
	 ('v46MvpJZjA','hamilton-sys-v1','Audy Beauchamp','AUBE','Nutri G','si0Z3eaIh0','PENDING','UNKNOWN','LD'),
	 ('Glbme6uDLo','patient-data-sync-v1','Betsy Bermãºdez','BEBE','Platinum Interior Design','cYZ6KQNbBC','PENDING','KNOWN','AD'),
	 ('yzRHjB5ktQ','automatic-sample-prep-exp-v1','Alicea Bolam','ALBO','Circuit Design','tn_oaClZKA','PENDING','UNKNOWN','ZD'),
	 ('OSipgZBfqW','pems-poc-sys-v1','Averil Bowman','AVBO','Better Business Ideas and Services','VPlhNl49kQ','PENDING','KNOWN','RS'),
	 ('Awkwq66b4J','sfc-pubsub-consumer-v1','Beilul Bennoune','BEBE','Libera','zvMc5iZs_y','DEPLOYED','UNKNOWN','ZD'),
	 ('H8Rfm7B0no','qd-exp-v1','Babbette Alegrias','BAAL','First Choice Yard Help','kgLEnTYb93','PENDING','KNOWN','ZD'),
	 ('Z6ldWPIdUT','sf-patient-sys-v1','Carree Antunez','CAAN','Datacorp','RYU2wb8w0A','PENDING','UNKNOWN','RS'),
	 ('pjGDLU3mgv','veeva-crm-snowflake-evntdriven-v1','Ardella Bahr','ARBA','Dynatronics Accessories','8w01HsWqn-','FAILED','KNOWN','CS');
INSERT INTO public.muleapplication (id,name,contactperson,contactpersoninitials,projectname,onboardingagreementid,status,category,costcenterlabel) VALUES
	 ('AzOZQctkk9','ioengage-sys-v1-v1','Ameline Baal','AMBA','Mission Realty','9wvz4vCn7M','PENDING','KNOWN','RS'),
	 ('suXMRm1TYb','gsa-ioengage-sys-v1','Ashil Bryan','ASBR','Brilliant Home Designs','ybPySOH1cI','PENDING','UNKNOWN','AD'),
	 ('iOuO5fiQjf','nn-patient-registration-sys-v1','Candie Anonymous','CAAN','Macroserve','Y_XJ_L57NX','FAILED','KNOWN','AD'),
	 ('yl3UmiekDx','otr-registration-v2','Carena Ascencio','CAAS','Eden Lawn Service','hb3SpUtLPE','FAILED','UNKNOWN','AD'),
	 ('jQOPyEcpDk','ioengage-sys-v1','Cahra Bergstein','CABE','Megatronic Plus','aw0qVnNefO','FAILED','KNOWN','CS'),
	 ('jH2LsaTloc','nn-datalake-ioccs-exp-api-v1','Antoinette Caraza','ANCA','Electronics Source','rUu9XX3Bza','PENDING','KNOWN','AD'),
	 ('hCYUDAH9y8','samples-prc-v1','Atlanta Abarca','ATAB','Custom Lawn Care','RD84wIHtqk','FAILED','KNOWN','LD'),
	 ('qaRHa-0cZj','mdm-read-api-v1','Barbabra Barbã©','BABA','Omni Source','vPg7-5GGYN','DEPLOYED','KNOWN','CS'),
	 ('i0BdxqwaQ9','arx-benefit-verification-v1','Alina Braunschwel','ALBR','Express Merchant Service','KPCtaDNpK3','FAILED','KNOWN','AD'),
	 ('qRXNFLJl7z','dummy-sys-v1','Barbaraanne Brotherton','BABR','Earthworks Garden Kare','PXhl71OZIX','FAILED','KNOWN','CS');
INSERT INTO public.muleapplication (id,name,contactperson,contactpersoninitials,projectname,onboardingagreementid,status,category,costcenterlabel) VALUES
	 ('WlgGNeVYHK','sfc-authentication-v1','Augusta Brawley','AUBR','A+ Investments','Kzwo5rzgH-','FAILED','UNKNOWN','ZD'),
	 ('qHpjMotiE7','ioccs-evntlg-databckp-prc-v1','Cassandra Bolin','CABO','Netcore','j9qTcHxrdE','FAILED','KNOWN','CS'),
	 ('jCe0foI5on','participants-prc-v1','Carmina Blanc','CABL','Micro Design','XIuIErf5t6','DEPLOYED','KNOWN','ZD'),
	 ('JnA1cYeWh9','otr-registration-v2-v1','Bellanca Benny','BEBE','Belle Ladi','oecR2-fNsJ','DEPLOYED','KNOWN','LD'),
	 ('9s7qBzHz1H','reference-360-sys-v1','Blake Biskay','BLBI','Planetbiz','v67jBP5PLA','PENDING','KNOWN','ZD'),
	 ('wQVDJdNpc2','sf-ioccs-platformevent-sys-v1','Athena Byrne','ATBY','Millenia Life','XkUUE6LDVA','DEPLOYED','UNKNOWN','LD'),
	 ('sEmuqbuDY2','mdm-party-prc-v1','Bobine Berdejo','BOBE','One-Up Realty','I2NEt__2rl','DEPLOYED','UNKNOWN','LD'),
	 ('2B9QFgNWBC','paperless-training-exp-v1','Carmencita Bayardo','CABA','Gas Depot','J9HU3Wr70F','PENDING','UNKNOWN','LD'),
	 ('huzjyPwppG','sfc-search-v1','Barbi Arroyo','BAAR','Advansed Teksyztems','2fiE27ZWfV','FAILED','KNOWN','CS'),
	 ('76aJk_8wXr','patient-management-v1','Bertine Bozic','BEBO','Omni Architectural Designs','43cGS1QZBa','DEPLOYED','UNKNOWN','LD');
INSERT INTO public.muleapplication (id,name,contactperson,contactpersoninitials,projectname,onboardingagreementid,status,category,costcenterlabel) VALUES
	 ('p7xqtWNa3D','cdr-static-test-v1','Amber Alger','AMAL','Excella','o5lptcLlUv','FAILED','KNOWN','CS'),
	 ('bIw4pvq0PG','gpp-planisware-prc-to-be-updated','Betsey Amigos','BEAM','Mikrotechnic','vkKt5jmj2t','FAILED','UNKNOWN','RS'),
	 ('H0xBKEJUt5','platform-events-develop-v1','Aubree Cancelado','AUCA','Corinthian Designs','4I65atlDhA','FAILED','KNOWN','AD'),
	 ('22WYyQt3GL','oce-sales-party-exp-v1','Aprilette Aistara','APAI','Netstars Matrix Design','8VUGhvY2VY','DEPLOYED','KNOWN','LD'),
	 ('Lpu1lXOlGq','exp-income-verification-v1','Alverta Cabrera','ALCA','Libera','3aQ-8nuR20','DEPLOYED','UNKNOWN','AD'),
	 ('ItnQBpVG5G','crx-registration-v1','Berny Bruner','BEBR','Edge Yard Service','T38rWoK2cr','PENDING','KNOWN','ZD'),
	 ('tyrCdTizjv','rddh-rim-sys-api-v1','Austine Bech','AUBE','Fragrant Flower Lawn Services','KUGv8cQXFx','FAILED','KNOWN','ZD'),
	 ('eJgooxw4xp','idq-registration-v1','Barb Ard','BAAR','Lawn N'' Order Garden Care','TqomD-F3X7','FAILED','UNKNOWN','LD'),
	 ('JJSvrDJPxi','globallims-prc-v1','Anthia Amansala','ANAM','Envirotecture Design Service','2BPeZyhli_','FAILED','KNOWN','RS'),
	 ('_CaarZyt5R','adb-service-v1','Auguste Birnbaum','AUBI','Happy Bear Investment','xa10aZCCiA','PENDING','KNOWN','CS');
INSERT INTO public.muleapplication (id,name,contactperson,contactpersoninitials,projectname,onboardingagreementid,status,category,costcenterlabel) VALUES
	 ('zDqHjVxZv_','monitoring-veevarim-nnedl-int-v1','Ann Butzer','ANBU','Knockout Kickboxing','KJx0wZlO4m','FAILED','KNOWN','AD'),
	 ('J5W9w7_RbM','rtsm-inbound-v1','Berte Bezborodoff','BEBE','Magik Grey','MMsBGVZbW2','PENDING','UNKNOWN','ZD'),
	 ('_r2EjFlUBC','veeva-vault-qd-sys-v1','Atlanta Cale','ATCA','Megatronic Plus','FgNqmRYdYT','PENDING','UNKNOWN','RS'),
	 ('mZfQ_pNUrR','nextgen-sys-v2','Abagael Behr','ABBE','Naturohair','-i0RtgU2ry','FAILED','KNOWN','RS'),
	 ('PpzbvQdow5','mdm-message-delivery-v1','Arden Aistara','ARAI','Edge Garden Services','jFmL2zD-Zq','FAILED','UNKNOWN','CS'),
	 ('Ll6xOkJ3T6','novodemo-sys-v1','Cassandry Brady','CABR','Bold Ideas','Qesjg1C_Oa','PENDING','UNKNOWN','CS'),
	 ('a7yrKkm5dz','trainings-prc-v1','Belvia Bennoune','BEBE','Magna Consulting','GqbQjFXOG7','FAILED','UNKNOWN','CS'),
	 ('6iGFwizG_Q','sap-material-master-prx-v1','Carolann Beauchamp','CABE','Integra Wealth Planners','glu1IiDqIt','PENDING','KNOWN','AD'),
	 ('U_1_X9tI63','nn-ioccs-sys-api-v1','Aliza Brent','ALBR','Friendly Advice','0eT-DSAzUP','DEPLOYED','UNKNOWN','CS'),
	 ('LsQVBDTrQ8','patient-safe-needledisposal-v1','Aimil Billingsley','AIBI','Opti-Tek','8x-MXkMrX-','PENDING','UNKNOWN','AD');
INSERT INTO public.muleapplication (id,name,contactperson,contactpersoninitials,projectname,onboardingagreementid,status,category,costcenterlabel) VALUES
	 ('eacTddAhTc','veeva-vault-registrations-prc-v1','Babara Arthur','BAAR','Monk Home Improvements','zu1oRdR3-3','FAILED','UNKNOWN','LD'),
	 ('Rm4w4RZZ2e','provider-management-v1','Ayn Aboud','AYAB','Castle Realty','2XV3fTK7y8','DEPLOYED','KNOWN','CS'),
	 ('ptqChRO_yY','mdm-ref-prc-v1','Alvinia Bolam','ALBO','Magna Wealth','Rk06oyGhaM','PENDING','KNOWN','ZD'),
	 ('6hab8ddnU7','novoglow-sys-v1','Aeriela Bernardini','AEBE','Gamma Gas','N_QLzjxSUO','PENDING','UNKNOWN','LD'),
	 ('vIq-f7aMlG','nl-meded-ioengage-sys-v1','Avis Alevizos','AVAL','Brilliant Home Designs','mOdfaiKCQ5','PENDING','UNKNOWN','AD'),
	 ('DzEHyU3svf','clinical-vault-data-sys-api-v1','Ami Basman','AMBA','Omni Tech Solutions','hInsffbBYD','DEPLOYED','UNKNOWN','AD'),
	 ('Pv2g4JehTc','sfc-token-v1','Anett Barcenas','ANBA','New World','F9_IWgef4N','FAILED','UNKNOWN','RS'),
	 ('IWETuE0zcy','cnm-registration-v1','Carroll Barbã©','CABA','Cut Rite Lawn Care','ga88BI1vwu','DEPLOYED','UNKNOWN','RS'),
	 ('IFIUYa44Dm','hcl-caseorder-prc-v1','Andriette Bad','ANBA','Full Color','-rzGYMgwvl','PENDING','KNOWN','RS'),
	 ('bFS7N06Nwk','clinical-data-pharmacm-prc-v1','Auroora Beckerman','AUBE','A+ Investments','uuz561c8oi','PENDING','KNOWN','LD');
INSERT INTO public.muleapplication (id,name,contactperson,contactpersoninitials,projectname,onboardingagreementid,status,category,costcenterlabel) VALUES
	 ('ldyA9L_tGM','nnameo-sm-aus-sco-v1','Bekki Bronstein','BEBR','Grass Roots Yard Services','miFdbVr_xx','FAILED','KNOWN','CS'),
	 ('qc9ub1bt2v','vev-registration-v1','Bellina Ahrens','BEAH','Happy Bear Investment','j65v4FV6fI','FAILED','UNKNOWN','ZD'),
	 ('Ez79P-NsWq','email-unsubscribe-v1','Beryle Bailey','BEBA','Destiny Realty Solutions','dm9PQrRdkJ','FAILED','UNKNOWN','AD'),
	 ('6GqDO7QGGt','platform-events-v1','Ailina Buckley','AIBU','Independent Investors','dWnewb8Mby','PENDING','UNKNOWN','LD'),
	 ('JFGW7p6VTW','sf-datavisualization-ioccs-v1','Amil Biersack','AMBI','Envirotecture Design Service','Mr2HKYJcMt','FAILED','UNKNOWN','LD'),
	 ('7EYFjWqFww','mdm-ref-exp-v1','Allis Brickley','ALBR','Monk Home Improvements','4v7Ow94Uio','FAILED','UNKNOWN','LD'),
	 ('yeURfO1SLI','npi-lookup-v1','Britteny Anonymous','BRAN','Netobill','6-vNpa5luE','DEPLOYED','KNOWN','ZD'),
	 ('TmQn-8HkqD','exd-ioengage-sys-v1','Adel Beaird','ADBE','Creative Wealth Management','9APbVTfhV5','PENDING','KNOWN','ZD'),
	 ('u6DTohkSf3','bsp-message-delivery-v1','Cairistiona Bina','CABI','Destiny Realty','yHg-WTQOoR','DEPLOYED','UNKNOWN','CS'),
	 ('RTz-u-ytGa','rtsm-outbound-v1','Ada Abrams','ADAB','Benesome','wH0BQs2_O2','PENDING','UNKNOWN','LD');
INSERT INTO public.muleapplication (id,name,contactperson,contactpersoninitials,projectname,onboardingagreementid,status,category,costcenterlabel) VALUES
	 ('96Pr5klA4X','map-management-sys-v1','Carline Adara','CAAD','Creative Wealth Management','ZCBxWtxBVw','DEPLOYED','UNKNOWN','CS'),
	 ('PkX07ZZWjM','clinical-vault-data-sys-v1','Alvera Alevizos','ALAL','Omni Realty','sibFnwQATn','FAILED','KNOWN','RS'),
	 ('BrAIalUmm_','patient-verification-exp-v1-v1','Britt Booz','BRBO','Beasts of Beauty','BX8UNmYA-0','PENDING','KNOWN','AD'),
	 ('6m0B45GrrU','novovision-ioengage-sys-v1','Antonella Agin','ANAG','Planet Profit','D99ymOiajt','FAILED','UNKNOWN','ZD'),
	 ('6H4l0XmEVD','map-metrics-acc-v1','Caren Ama','CAAM','Manu Connection','OgCGGm1ybM','DEPLOYED','UNKNOWN','LD'),
	 ('3RLpNSQO5Q','labvantage-sys-v1','Andriana Bri','ANBR','Opti-Tek','plLhAMHK_O','FAILED','KNOWN','CS'),
	 ('Nf0yD8TmIt','phl-registration-v1','Alvera Bruno','ALBR','Helios Air','S2lmj5Vx-E','PENDING','KNOWN','LD'),
	 ('9UxhtTomRu','patient-coach-v1','Alisun Baltzley','ALBA','Las Vegas Yard Management','wbXpLjCQen','FAILED','UNKNOWN','CS'),
	 ('ZTjF60EmRs','mdm-registration-v1','Cammi Alengria','CAAL','Integra Investment Plan','QRMZ8u7e9V','PENDING','KNOWN','AD'),
	 ('YP7Ubv0Lf_','ioccs-eu-translate-utility-v1','Annemarie Borock','ANBO','Magna Gases','ZJ0xdqs4GP','PENDING','KNOWN','CS');
INSERT INTO public.muleapplication (id,name,contactperson,contactpersoninitials,projectname,onboardingagreementid,status,category,costcenterlabel) VALUES
	 ('xTNuWWvhZq','uagk-test-2023020802-poc-v1','Ardene Bishop','ARBI','Helios Air','XTW3aO5UzI','PENDING','UNKNOWN','AD'),
	 ('koIAo2jx8L','qd-prc-v1','Beatriz Bracamonte','BEBR','Destiny Realty','urY5xyH2s_','PENDING','UNKNOWN','CS'),
	 ('gZRufCI4_9','ioccs-materialorder-prc-v1','Ardelia Abrams','ARAB','Indiewealth','i5qC8Ex5fl','PENDING','UNKNOWN','ZD'),
	 ('JfWs57w4rv','clinical-data-exp-v2','Alvinia Barnett','ALBA','Integra Design','y0Z9_EWPyZ','PENDING','UNKNOWN','CS'),
	 ('xCPHfE3HNk','clinical-data-exp-v1','Beckie Blomqvist','BEBL','Monit','qHcGgJcf74','DEPLOYED','KNOWN','CS'),
	 ('KiaLmIedFp','repsco-ioengage-sys-v1','Camellia Annitto','CAAN','Life Plan Counselling','19RiTEXWoY','DEPLOYED','UNKNOWN','CS'),
	 ('DOWc91uSoQ','patient-verification-exp-v1','Alyson Canto','ALCA','Environ Architectural Design','obeEtGCc0H','DEPLOYED','KNOWN','CS'),
	 ('o5MnUowv5Q','ioengage-ioccs-prc-v1','Amy Ampudia','AMAM','Adaptabiz','d7q-hS3vcF','DEPLOYED','KNOWN','ZD'),
	 ('gN7uCtFqBJ','notification-management-v1','Carolyne Berdejo','CABE','Excella','4zJTs6Yi4v','DEPLOYED','KNOWN','CS'),
	 ('TSbF8Fw-MY','meet-oksearch-ioengage-sys-v1','Anneliese Carbone','ANCA','Creative Wealth','Yq4m9dh5sp','PENDING','KNOWN','ZD');
INSERT INTO public.muleapplication (id,name,contactperson,contactpersoninitials,projectname,onboardingagreementid,status,category,costcenterlabel) VALUES
	 ('bosqgtCqg0','mdm-ref-exp-first-v1','Aindrea Blein','AIBL','Konsili','6m1d5CqKTQ','FAILED','UNKNOWN','LD'),
	 ('zCWEg34VTY','crx-file-feed-v1','Adoree Brinkley','ADBR','Magik Gray','Lgy64K1OsK','PENDING','UNKNOWN','AD'),
	 ('flQZswH-9p','nextgen-ioccs-v1','Anallese Athureliya','ANAT','ManPower','qQBWdlqL57','PENDING','KNOWN','LD'),
	 ('bakyoS5xUE','mdm-jms-consumer-v1','Belia Andrea','BEAN','Asian Answers','iva2YmZOyo','PENDING','KNOWN','AD'),
	 ('_wWGlM4ODI','lims-sys-v1','Adena Boveri','ADBO','Enviro Architectural Designs','Ex0lsgwj9L','DEPLOYED','UNKNOWN','CS'),
	 ('-Y1RFq8JmQ','leapwork-sys-v1','Caresse Andree','CAAN','Monk Home Loans','2jZwfu3J-s','DEPLOYED','UNKNOWN','LD'),
	 ('T8Xjs32Vrm','deltaload-ctms-nnedl-int-v1','Biddy Alfond','BIAL','Cut Rite','Mhct3pyEZD','DEPLOYED','KNOWN','LD'),
	 ('cScF6Lgidq','uagk-test-2023020801-v1','Arlana Carli','ARCA','Formula Gray','ZSHsZK0P4n','PENDING','KNOWN','RS'),
	 ('7X1harwXa2','sf-patient-sys-api-v1','Alexa Book','ALBO','Dynatronics Accessories','2qrGSzUKJS','FAILED','UNKNOWN','RS'),
	 ('4s7Ults_4s','rxc-service-v1','Agnella Baxter','AGBA','Grey Fade','4RLKG9I4xD','DEPLOYED','KNOWN','CS');
INSERT INTO public.muleapplication (id,name,contactperson,contactpersoninitials,projectname,onboardingagreementid,status,category,costcenterlabel) VALUES
	 ('uXyhb9CH4k','datalake-ioccs-v1','Addie Bussey','ADBU','Macroserve','48OlmuOQ5b','DEPLOYED','KNOWN','RS'),
	 ('guuU-zlxlZ','clinical-vault-data-inbound-v1','Austina Camara','AUCA','Envirotecture Design','aQ_kSlqxIi','DEPLOYED','UNKNOWN','ZD'),
	 ('qguhlYxbHJ','map-vcore-invoicing-v1','Berta Bishri','BEBI','Fellowship Investments','AFF2fkUSq9','DEPLOYED','UNKNOWN','CS'),
	 ('COj5_lxW-3','pmt-message-delivery-v1','Brunhilda Ashton','BRAS','Best Biz Survis','C3z85-ryJd','PENDING','KNOWN','ZD'),
	 ('GGYh6Jv0y4','map-pilot-application-v1','Ajay Ascoe','AJAS','Lawnscape Garden Maintenance','utbgV_QLRH','PENDING','UNKNOWN','AD'),
	 ('LpGLc0RTt-','aws-services-v1','Barrie Becker','BABE','Intelli Wealth Group','Y5TP3fIlLr','PENDING','KNOWN','CS'),
	 ('Ea2XtiX2om','veeva-crm-snowflake-proc-v1','Analiese Andsaldi','ANAN','Ejecta','DWdck2zUx1','PENDING','UNKNOWN','CS'),
	 ('9sHYvGa_29','oce-mktng-partyload-sys-v1','Belia Carissa','BECA','Gas Legion','XXKXkgYuvR','DEPLOYED','UNKNOWN','AD'),
	 ('ZG42ZopuJy','web-campaign-management-v1','Babara Antoci','BAAN','Body Toning','nCqUNecsgq','PENDING','UNKNOWN','RS'),
	 ('BPSHPBoeuV','concur-ioengage-sys-v1','Audrye Andsaldi','AUAN','Muscle Factory','bthcyi7wBw','DEPLOYED','UNKNOWN','AD');
INSERT INTO public.muleapplication (id,name,contactperson,contactpersoninitials,projectname,onboardingagreementid,status,category,costcenterlabel) VALUES
	 ('fdvNUWu7Sc','sfc-token-test-v1','Ara Bhojwani','ARBH','Friendly Interior Design','FNKAwYBNfV','FAILED','UNKNOWN','AD'),
	 ('tPe7pubYCo','veeva-vault-rim-sys-v1','Caro Alverã ','CAAL','Merrymaking','K5x-mFw3GM','PENDING','KNOWN','ZD'),
	 ('9Yb1SnXKby','product-verification-mobile-v1','Blakeley Brecht','BLBR','Atlas Architectural Designs','E8LrzJXSur','DEPLOYED','UNKNOWN','LD'),
	 ('rkuoyodXIq','patient-token-cleanup-v1','Carmel Cardona','CACA','Monk Home Funding Services','bKxGmgROzq','PENDING','KNOWN','AD'),
	 ('htrv8Lz10P','mi-dms-24a-sys-v1','Ardelis Bonnet','ARBO','Friendly Interior Design','-xMyEt2n8C','PENDING','KNOWN','LD'),
	 ('oHBT7YqpUa','scifi-exp-v1','Ardelia Abbott','ARAB','New World Realty','KbgV6d-XCs','FAILED','UNKNOWN','ZD'),
	 ('OwTSv7VP6K','ioccs-materialorder-prc-v2','Angy Belz','ANBE','Infinite Wealth Planners','Nu6_S4Tj-M','PENDING','UNKNOWN','CS'),
	 ('x3X2KAObNr','veeva-vault-clinical-prc-v1','Audre Atteberry','AUAT','Corinthian Designs','HpiuBsVSw-','FAILED','KNOWN','AD'),
	 ('KWzxLZbcsv','iis-dotnet-mule-test-v1','Agna Brook','AGBR','Omni Tech Solutions','29eQhOfI7f','FAILED','UNKNOWN','RS'),
	 ('xhmSwx22ut','data-mig-oracle-snowflake-proc-v1','Beckie Arjona','BEAR','Integra Wealth','SKlrB7n52r','FAILED','KNOWN','AD');
INSERT INTO public.muleapplication (id,name,contactperson,contactpersoninitials,projectname,onboardingagreementid,status,category,costcenterlabel) VALUES
	 ('qnf7bSv2zY','patient-authentication-v1','Caro Bressan','CABR','New World','K-LuUKzP2p','DEPLOYED','UNKNOWN','CS'),
	 ('HHxMCV0x8w','msgraph-sendemail-sys-v1','Avis Bartell','AVBA','Acuserv','uPYjpKAdv4','FAILED','UNKNOWN','ZD'),
	 ('U-X9n84c66','clinical-data-database-sys-v1','Annmarie Abel','ANAB','Ejecta','X1o_ADcTbU','FAILED','UNKNOWN','ZD'),
	 ('7faiCvYSaB','deltaload-queue-publisher-v1','Aubrette Brandon','AUBR','Magik Grey','LJKdf3JBPO','DEPLOYED','UNKNOWN','AD'),
	 ('MRaMUAGtwF','otr-registration-v1','Alys Ahmed','ALAH','Gas Depot','-I_hdwnuk5','PENDING','KNOWN','ZD'),
	 ('XwQA6Q_fNQ','sf-ioccs-sys-v1','Carroll Barbara','CABA','Best Biz Survis','MmORAidB13','PENDING','UNKNOWN','ZD'),
	 ('UdLEdOAta5','nnltm-ioevents-co-v1','Ameline Byargeon','AMBY','Datacorp','R8Mc0uxFNb','FAILED','KNOWN','CS'),
	 ('U18sK7WXv5','clinical-data-batch-prc-v1','Avivah Andres','AVAN','Acuserv','KKhV593pGI','DEPLOYED','KNOWN','CS'),
	 ('l2mtjOuGZv','calyx-sys-v1','Beverie Bales','BEBA','Integra Design','v7mra8gcLh','PENDING','KNOWN','AD'),
	 ('7a57-tQUPW','sap-attp-product-verification-v2','Andriana Alan','ANAL','Lawn N'' Order Garden Care','v2QCNIfwQI','DEPLOYED','KNOWN','CS');
INSERT INTO public.muleapplication (id,name,contactperson,contactpersoninitials,projectname,onboardingagreementid,status,category,costcenterlabel) VALUES
	 ('slRj26_W6z','azenta-sys-v1','Alta Acra','ALAC','Plan Smart Partner','Z1hgWzgGd-','PENDING','KNOWN','CS');
